/**********************************/
/* テーブル名: 預金口座 */
/**********************************/
CREATE TABLE TBL_ACCOUNT(
		BRANCH_NO CHARACTER(3) NOT NULL,
		ACCOUNT_NO CHARACTER(7) NOT NULL,
		ACCOUNT_NAME VARCHAR(100) NOT NULL,
		ACCOUNT_BALANCE BIGINT NOT NULL DEFAULT 0
);


ALTER TABLE TBL_ACCOUNT ADD CONSTRAINT IDX_TBL_ACCOUNT_PK PRIMARY KEY (BRANCH_NO, ACCOUNT_NO);

